name: Make slides

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "::set-env name=FILELIST::$(printf '"%s" '/seminar*/slides.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: -t beamer --output=${{ env.FILELIST }}.pdf ${{ env.FILELIST }}
