name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: run loop
        env:
         FILES: /seminar1/slides.md
        uses: docker://pandoc/core:2.9
        run: for f in $FILES; do pandoc -t beamer $f -o $f.pdf; done
        
