name: Make seminar slides from markdown

on: push

jobs:
  make_seminar1_slides:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./seminar1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: slides
      - uses: docker://pandoc/latex:2.9
        with:
          args: -t beamer --output=slides.md.pdf slides.md
      - uses: actions/upload-artifact@v2
        with:
          name: seminar-slides
          path: slides.md.pdf
